# Generated by Django 4.2.7 on 2023-11-12 11:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('is_active', models.CharField(default=True)),
                ('date_of_creat', models.DateTimeField()),
                ('date_of_latest_update', models.DateTimeField(default='12/11/2023')),
                ('balance', models.IntegerField()),
                ('location', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CarShowRoom',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='showroom.basemodel')),
                ('min_price_of_car', models.IntegerField()),
                ('max_price_of_car', models.IntegerField()),
                ('min_year_of_car_realise', models.DateTimeField(validators=[django.core.validators.MaxValueValidator(2023)])),
                ('max_year_of_car_realise', models.DateTimeField(validators=[django.core.validators.MaxValueValidator(2023)])),
            ],
            bases=('showroom.basemodel',),
        ),
    ]
