# Generated by Django 4.2.7 on 2023-11-13 10:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarShowRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_of_creat', models.DateTimeField()),
                ('date_of_latest_update', models.DateTimeField(default='13/11/2023')),
                ('balance', models.IntegerField()),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('min_price_of_car', models.IntegerField()),
                ('max_price_of_car', models.IntegerField()),
                ('min_year_of_car_realise', models.DateTimeField(validators=[django.core.validators.MaxValueValidator(2023)])),
                ('max_year_of_car_realise', models.DateTimeField(validators=[django.core.validators.MaxValueValidator(2023)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarShowRoomStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField()),
                ('car_price', models.IntegerField()),
                ('amount_of_cars_of_this_model', models.IntegerField()),
                ('year_of_car_realise', models.IntegerField(default=2023)),
                ('show_room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='showroom.carshowroom')),
            ],
        ),
    ]
