# Generated by Django 4.2.7 on 2023-11-13 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_remove_carshowroom_max_year_of_car_realise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshowroom',
            name='max_year_of_car_realise',
            field=models.IntegerField(default=2023, validators=[django.core.validators.MaxValueValidator(2023)]),
        ),
        migrations.AddField(
            model_name='carshowroom',
            name='min_year_of_car_realise',
            field=models.IntegerField(default=2023, validators=[django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
