# Generated by Django 4.2.7 on 2023-11-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_carshowroomstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshowroomstock',
            name='year_of_car_realise',
            field=models.IntegerField(default=2023),
        ),
    ]
