# Generated by Django 4.2.7 on 2023-11-15 09:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0007_alter_carshowroom_date_of_creat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carshowroom',
            name='date_of_creat',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 12, 5, 45, 517791)),
        ),
        migrations.AlterField(
            model_name='carshowroom',
            name='date_of_latest_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 12, 5, 45, 517791)),
        ),
        migrations.AlterField(
            model_name='carshowroomstock',
            name='show_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.carshowroom'),
        ),
    ]
