# Generated by Django 4.2.7 on 2023-11-16 09:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0009_alter_carshowroom_date_of_creat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carshowroom',
            name='date_of_creat',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 16, 12, 26, 5, 496972)),
        ),
        migrations.AlterField(
            model_name='carshowroom',
            name='date_of_latest_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 16, 12, 26, 5, 496972)),
        ),
        migrations.AlterField(
            model_name='carshowroomstock',
            name='year_of_car_realise',
            field=models.IntegerField(default=2023, validators=[django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
