# Generated by Django 4.2.7 on 2023-11-16 09:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0010_alter_carshowroom_date_of_creat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carshowroom',
            name='max_year_of_car_realise',
        ),
        migrations.RemoveField(
            model_name='carshowroom',
            name='min_year_of_car_realise',
        ),
        migrations.RemoveField(
            model_name='carshowroomstock',
            name='year_of_car_realise',
        ),
        migrations.AddField(
            model_name='carshowroom',
            name='max_year_of_car_release',
            field=models.IntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)]),
        ),
        migrations.AddField(
            model_name='carshowroom',
            name='min_year_of_car_release',
            field=models.IntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)]),
        ),
        migrations.AddField(
            model_name='carshowroomstock',
            name='year_of_car_release',
            field=models.IntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)]),
        ),
        migrations.AlterField(
            model_name='carshowroom',
            name='date_of_creat',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 16, 12, 32, 40, 309795)),
        ),
        migrations.AlterField(
            model_name='carshowroom',
            name='date_of_latest_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 16, 12, 32, 40, 309795)),
        ),
    ]
