# Generated by Django 4.2.7 on 2023-11-20 09:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0018_alter_buyer_date_of_creat_and_more'),
        ('showroom', '0019_alter_carshowroom_date_of_creat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshowroom',
            name='buyers_from_showroom',
            field=models.ManyToManyField(to='buyer.buyer'),
        ),
        migrations.AlterField(
            model_name='carshowroom',
            name='date_of_creat',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 12, 20, 24, 317608)),
        ),
        migrations.AlterField(
            model_name='carshowroom',
            name='date_of_latest_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 12, 20, 24, 317608)),
        ),
        migrations.AlterField(
            model_name='carshowroomstock',
            name='date_of_creat',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 12, 20, 24, 327619)),
        ),
        migrations.AlterField(
            model_name='carshowroomstock',
            name='date_of_latest_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 12, 20, 24, 327619)),
        ),
        migrations.CreateModel(
            name='TransactionFromShowroomToBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_transaction', models.DateField(default=datetime.datetime(2023, 11, 20, 12, 20, 24, 327619))),
                ('car_model', models.CharField()),
                ('price_of_transactions', models.PositiveIntegerField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.buyer')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.carshowroom')),
            ],
            options={
                'ordering': ['-date_of_transaction'],
            },
        ),
    ]
