# Generated by Django 4.2.7 on 2023-11-20 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0020_carshowroom_buyers_from_showroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carshowroom',
            name='date_of_creat',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 12, 23, 17, 44234)),
        ),
        migrations.AlterField(
            model_name='carshowroom',
            name='date_of_latest_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 12, 23, 17, 44234)),
        ),
        migrations.AlterField(
            model_name='carshowroomstock',
            name='date_of_creat',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 12, 23, 17, 44234)),
        ),
        migrations.AlterField(
            model_name='carshowroomstock',
            name='date_of_latest_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 12, 23, 17, 44234)),
        ),
        migrations.AlterField(
            model_name='transactionfromshowroomtobuyer',
            name='date_of_transaction',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 12, 23, 17, 44234)),
        ),
    ]
