# Generated by Django 4.2.7 on 2023-11-12 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField()),
                ('car_price', models.IntegerField()),
                ('producer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='producer.producer')),
            ],
        ),
    ]
