# Generated by Django 4.2.7 on 2023-11-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0003_carshowroomstock_year_of_car_realise'),
        ('producer', '0002_producerstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='buyers_from_producer',
            field=models.ManyToManyField(to='showroom.carshowroom'),
        ),
        migrations.AddField(
            model_name='producerstock',
            name='year_of_car_realise',
            field=models.IntegerField(default=2023),
        ),
    ]
