# Generated by Django 4.2.7 on 2023-11-16 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0009_remove_producerstock_year_of_car_realise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='date_of_creat',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 16, 12, 34, 14, 864575)),
        ),
        migrations.AlterField(
            model_name='producer',
            name='date_of_latest_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 16, 12, 34, 14, 864575)),
        ),
    ]
