# Generated by Django 4.2.7 on 2023-11-17 12:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0013_alter_producer_date_of_creat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='date_of_creat',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 15, 52, 2, 933463)),
        ),
        migrations.AlterField(
            model_name='producer',
            name='date_of_latest_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 15, 52, 2, 933463)),
        ),
        migrations.AlterField(
            model_name='producerstock',
            name='date_of_creat',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 15, 52, 2, 943464)),
        ),
        migrations.AlterField(
            model_name='producerstock',
            name='date_of_latest_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 15, 52, 2, 943464)),
        ),
        migrations.AlterField(
            model_name='producerstock',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_stock', to='producer.producer'),
        ),
    ]
