# Generated by Django 4.2.7 on 2023-11-19 13:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0018_alter_carshowroom_date_of_creat_and_more'),
        ('producer', '0015_remove_transactionproducertoshowroom_showroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionproducertoshowroom',
            name='showroom_id',
        ),
        migrations.AddField(
            model_name='transactionproducertoshowroom',
            name='showroom',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='showroom.carshowroom'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='date_of_creat',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 16, 49, 34, 659108)),
        ),
        migrations.AlterField(
            model_name='producer',
            name='date_of_latest_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 16, 49, 34, 659108)),
        ),
        migrations.AlterField(
            model_name='producerstock',
            name='date_of_creat',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 16, 49, 34, 669101)),
        ),
        migrations.AlterField(
            model_name='producerstock',
            name='date_of_latest_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 16, 49, 34, 669101)),
        ),
        migrations.AlterField(
            model_name='transactionproducertoshowroom',
            name='date_of_transaction',
            field=models.DateTimeField(default='19/11/2023'),
        ),
    ]
