# Generated by Django 4.2.7 on 2023-11-19 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0016_remove_transactionproducertoshowroom_showroom_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='date_of_creat',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 17, 46, 21, 755212)),
        ),
        migrations.AlterField(
            model_name='producer',
            name='date_of_latest_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 17, 46, 21, 755212)),
        ),
        migrations.AlterField(
            model_name='producerstock',
            name='date_of_creat',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 17, 46, 21, 765213)),
        ),
        migrations.AlterField(
            model_name='producerstock',
            name='date_of_latest_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 17, 46, 21, 765213)),
        ),
        migrations.AlterField(
            model_name='transactionproducertoshowroom',
            name='date_of_transaction',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 17, 46, 21, 765213)),
        ),
    ]
