services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=car_showroom_project
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwertyukmnb
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=car_showroom_project
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwertyukmnb
    depends_on:
      - db
