# Generated by Django 4.2.7 on 2023-11-12 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarShowRoomStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField()),
                ('car_price', models.IntegerField()),
                ('amount_of_cars_of_this_model', models.IntegerField()),
                ('show_room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='showroom.carshowroom')),
            ],
        ),
    ]
