# Generated by Django 4.2.7 on 2023-11-27 18:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("buyer", "0001_initial"),
        ("showroom", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fabric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("date_of_creat", models.DateTimeField()),
                ("date_of_latest_update", models.DateTimeField()),
                ("name", models.CharField()),
                ("balance", models.IntegerField(default=0)),
                ("location", django_countries.fields.CountryField(blank=True, max_length=2)),
                (
                    "show_rooms",
                    models.ManyToManyField(related_name="fabric_show_rooms", to="showroom.showroom"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("producer_to_showroom", "Producer to Showroom"),
                            ("showroom_to_buyer", "Showroom to Buyer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateTimeField()),
                ("model", models.CharField()),
                ("price", models.PositiveIntegerField()),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer_transactions",
                        to="buyer.buyer",
                    ),
                ),
                (
                    "fabric",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fabric_transactions",
                        to="fabric.fabric",
                    ),
                ),
                (
                    "showroom",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="showroom_transactions",
                        to="showroom.showroom",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="FabricCars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("date_of_creat", models.DateTimeField()),
                ("date_of_latest_update", models.DateTimeField()),
                ("model", models.CharField()),
                ("price", models.IntegerField()),
                (
                    "year_of_release",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2023),
                        ]
                    ),
                ),
                (
                    "fabric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fabric_cars",
                        to="fabric.fabric",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
