# Generated by Django 4.2.7 on 2023-11-12 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('showroom', '0002_carshowroomstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='showroom.basemodel')),
            ],
            bases=('showroom.basemodel',),
        ),
        migrations.CreateModel(
            name='TransactionFromShowroomToBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_transaction', models.DateField(default='12/11/2023')),
                ('car_model', models.CharField()),
                ('price_of_transactions', models.PositiveIntegerField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.buyer')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.carshowroom')),
            ],
            options={
                'ordering': ['-date_of_transaction'],
            },
        ),
    ]
