# Generated by Django 4.2.7 on 2023-11-13 10:56

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_of_creat', models.DateTimeField()),
                ('date_of_latest_update', models.DateTimeField(default='13/11/2023')),
                ('balance', models.IntegerField()),
                ('location', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionFromShowroomToBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_transaction', models.DateField(default='13/11/2023')),
                ('car_model', models.CharField()),
                ('price_of_transactions', models.PositiveIntegerField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.buyer')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.carshowroom')),
            ],
            options={
                'ordering': ['-date_of_transaction'],
            },
        ),
    ]
